/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stan (https://sketchfab.com/Stas_SayHallo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-dragon-97d00c182fa24fa4838493c41ad8e52c
Title: Stylized Dragon
*/

import  { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import dragon from '../assets/3d/stylized_dragon.glb'

export function ContactDragon({currentAnimation,...props}) {
    console.log("currentAnimation",currentAnimation)
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(dragon)
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    Object.values(actions).forEach((action) => action.stop());
    if(actions[currentAnimation]){
        actions[currentAnimation].play()
    }
   
},[actions,currentAnimation])

  return (
    <group ref={group} {...props} dispose={null} position={[-1,-1,1]} rotation={[.3,-0.5,0]}scale={1}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
          <group name="10fc9da1d1014ce0868a6f1565d17c14fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Dragon_body"
                  position={[0, 1671.56, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Armature"
                  position={[0, 596.204, -1228.461]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.dragon_body}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[0, 1671.559, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stylized_dragon.glb')
